version: '3.9'

services:
  flask-app:
    container_name: flask
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - 8001:8000
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    build: 
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - 3307:3306
    env_file:
      - .env
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:


